waypoints:
- latitude: 50.0468
  longitude: 22.007
  yaw: 0.0
waypoints:
- latitude: 0.0468
  longitude: 22.007
  yaw: 0.0
waypoints:
- latitude: 50.0468
  longitude: 2.007
  yaw: 0.0
waypoints:
- latitude: 250.0468
  longitude: 22.007
  yaw: 0.0
waypoints:
- latitude: 50.0468
  longitude: 2.007
  yaw: 0.0
waypoints:
- latitude: 0.0468
  longitude: 22.007
  yaw: 0.0