/oak_d_lite:
  ros__parameters:
    camera:
      i_mx_id: 1944301041FCD22600
      i_nn_type: rgb
    left:
      i_resolution: '480'
    right:
      i_resolution: '480'
    nn:
      i_nn_config_path: depthai_ros_driver/yolo
# /oak_d_w:
#   ros__parameters:
#     camera:
#       i_mx_id: 18443010814D3AF500
#       i_nn_type: rgb
#     nn:
#       i_nn_config_path: depthai_ros_driver/segmentation
# /oak_d_pro:
#   ros__parameters:
#     camera:
#       i_mx_id: 1944301051FB4D1300
#     nn:
#       i_nn_config_path: depthai_ros_driver/mobilenet
